#!/bin/bash
touch /etc/yum.repos.d/OpenHPC.repo
echo "[OpenHPC]" > /etc/yum.repos.d/OpenHPC.repo
echo "name=OpenHPC-1.3 - Base" >> /etc/yum.repos.d/OpenHPC.repo
echo "baseurl=http://13.71.5.143/OpenHPC:/1.3/CentOS_7" >> /etc/yum.repos.d/OpenHPC.repo
echo "gpgcheck=0" >> /etc/yum.repos.d/OpenHPC.repo
echo "gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-1" >> /etc/yum.repos.d/OpenHPC.repo

echo "[OpenHPC-updates]" >> /etc/yum.repos.d/OpenHPC.repo
echo "name=OpenHPC-1.3 - Updates" >> /etc/yum.repos.d/OpenHPC.repo
echo "baseurl=http://13.71.5.143/OpenHPC:/1.3/updates/CentOS_7" >> /etc/yum.repos.d/OpenHPC.repo
echo "gpgcheck=0" >> /etc/yum.repos.d/OpenHPC.repo
echo "gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-1" >> /etc/yum.repos.d/OpenHPC.repo

#sudo cp -L -f $DIB_YUM_REPO_CONF $TMP_MOUNT_PATH/etc/yum.repos.d/OpenHPC.repo
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# here install HPC Orchestrator release TODO.
